apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "846"
  creationTimestamp: "2021-12-20T08:41:40Z"
  generation: 849
  labels:
    app: m1-go-deployment-tinghai
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:progressDeadlineSeconds": {}
          "f:replicas": {}
          "f:revisionHistoryLimit": {}
          "f:selector":
            "f:matchLabels":
              .: {}
              "f:app": {}
          "f:strategy":
            "f:rollingUpdate":
              .: {}
              "f:maxSurge": {}
              "f:maxUnavailable": {}
            "f:type": {}
          "f:template":
            "f:metadata":
              "f:annotations": {}
              "f:labels":
                .: {}
                "f:app": {}
            "f:spec":
              "f:containers":
                'k:{"name":"idd-go-backend"}':
                  .: {}
                  "f:command": {}
                  "f:env":
                    .: {}
                    'k:{"name":"aliyun_logs_dev-hipcc-go-backend"}':
                      .: {}
                      "f:name": {}
                  "f:imagePullPolicy": {}
                  "f:name": {}
                  "f:ports":
                    .: {}
                    'k:{"containerPort":80,"protocol":"TCP"}':
                      .: {}
                      "f:containerPort": {}
                      "f:protocol": {}
                  "f:resources":
                    .: {}
                    "f:limits":
                      .: {}
                      "f:cpu": {}
                      "f:memory": {}
                    "f:requests":
                      .: {}
                      "f:cpu": {}
                      "f:memory": {}
                  "f:terminationMessagePath": {}
                  "f:terminationMessagePolicy": {}
                  "f:volumeMounts":
                    .: {}
                    'k:{"mountPath":"/srv/hipcc_go_backend/configs/project.yml"}':
                      .: {}
                      "f:mountPath": {}
                      "f:name": {}
                      "f:subPath": {}
                    'k:{"mountPath":"/srv/hipcc_go_backend/data/logs/project/"}':
                      .: {}
                      "f:mountPath": {}
                      "f:name": {}
              "f:dnsPolicy": {}
              "f:restartPolicy": {}
              "f:schedulerName": {}
              "f:securityContext": {}
              "f:terminationGracePeriodSeconds": {}
              "f:volumes":
                .: {}
                'k:{"name":"volume-1639990723227"}':
                  .: {}
                  "f:configMap":
                    .: {}
                    "f:defaultMode": {}
                    "f:name": {}
                  "f:name": {}
                'k:{"name":"volumn-sls-16399907553930"}':
                  .: {}
                  "f:emptyDir": {}
                  "f:name": {}
      manager: Apache-HttpClient
      operation: Update
      time: "2021-12-23T10:46:08Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:spec":
          "f:template":
            "f:metadata":
              "f:annotations":
                "f:redeploy-timestamp": {}
            "f:spec":
              "f:containers":
                'k:{"name":"idd-go-backend"}':
                  "f:env":
                    'k:{"name":"aliyun_logs_dev-hipcc-go-backend"}':
                      "f:value": {}
                    'k:{"name":"aliyun_logs_dev-m1-go-deployment"}':
                      .: {}
                      "f:name": {}
                      "f:value": {}
                  "f:image": {}
                  "f:volumeMounts":
                    'k:{"mountPath":"/etc/ssl/certs/GlobalSignRootCA.pem"}':
                      .: {}
                      "f:mountPath": {}
                      "f:name": {}
                      "f:subPath": {}
                    'k:{"mountPath":"/srv/hipcc_go_backend/logs/"}':
                      .: {}
                      "f:mountPath": {}
                      "f:name": {}
              "f:hostAliases":
                .: {}
                'k:{"ip":"172.17.6.3"}':
                  .: {}
                  "f:hostnames": {}
                  "f:ip": {}
              "f:volumes":
                'k:{"name":"volume-1641368108671"}':
                  .: {}
                  "f:configMap":
                    .: {}
                    "f:defaultMode": {}
                    "f:name": {}
                  "f:name": {}
                'k:{"name":"volumn-sls-16678125896630"}':
                  .: {}
                  "f:emptyDir": {}
                  "f:name": {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: "2022-11-24T03:10:55Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:deployment.kubernetes.io/revision": {}
        "f:status":
          "f:availableReplicas": {}
          "f:conditions":
            .: {}
            'k:{"type":"Available"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"Progressing"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:observedGeneration": {}
          "f:readyReplicas": {}
          "f:replicas": {}
          "f:updatedReplicas": {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-11-24T03:11:13Z"
  name: m1-go-deployment-tinghai
  namespace: dev
  resourceVersion: "3081360436"
  selfLink: /apis/apps/v1/namespaces/dev/deployments/m1-go-deployment-tinghai
  uid: 86d07e05-397d-48cf-8b33-27b83021df24
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: m1-go-deployment-tinghai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: "1669259454582"
      labels:
        app: m1-go-deployment-tinghai
    spec:
      containers:
        - command:
            - /srv/hipcc_go_backend/app
          env:
            - name: aliyun_logs_dev-hipcc-go-backend
              value: /srv/hipcc_go_backend/logs/*.log
            - name: aliyun_logs_dev-m1-go-deployment
              value: stdout
          image: >-
            registry-vpc.cn-beijing.aliyuncs.com/galixir/hipcc_go_backend:v2.2.8_switch
          imagePullPolicy: Always
          name: idd-go-backend
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /srv/hipcc_go_backend/configs/project.yml
              name: volume-1639990723227
              subPath: project.yml
            - mountPath: /srv/hipcc_go_backend/data/logs/project/
              name: volumn-sls-16399907553930
            - mountPath: /etc/ssl/certs/GlobalSignRootCA.pem
              name: volume-1641368108671
              subPath: GlobalSignRootCA.pem
            - mountPath: /srv/hipcc_go_backend/logs/
              name: volumn-sls-16678125896630
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
            - smtp.qiye.aliyun.com
          ip: 172.17.6.3
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: hipcc-backend-config
          name: volume-1639990723227
        - emptyDir: {}
          name: volumn-sls-16399907553930
        - configMap:
            defaultMode: 420
            name: globalsign-root-ca
          name: volume-1641368108671
        - emptyDir: {}
          name: volumn-sls-16678125896630
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-07-20T09:58:50Z"
      lastUpdateTime: "2022-07-20T09:58:50Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-12-22T06:38:45Z"
      lastUpdateTime: "2022-11-24T03:11:13Z"
      message: ReplicaSet "m1-go-deployment-tinghai-5dd9cf74fc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 849
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
